# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/notebooks', type: :request do
  # Notebook. As you add validations to Notebook, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Notebook.create! valid_attributes
      get notebooks_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      notebook = Notebook.create! valid_attributes
      get notebook_url(notebook)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_notebook_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'render a successful response' do
      notebook = Notebook.create! valid_attributes
      get edit_notebook_url(notebook)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Notebook' do
        expect do
          post notebooks_url, params: { notebook: valid_attributes }
        end.to change(Notebook, :count).by(1)
      end

      it 'redirects to the created notebook' do
        post notebooks_url, params: { notebook: valid_attributes }
        expect(response).to redirect_to(notebook_url(Notebook.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Notebook' do
        expect do
          post notebooks_url, params: { notebook: invalid_attributes }
        end.to change(Notebook, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post notebooks_url, params: { notebook: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested notebook' do
        notebook = Notebook.create! valid_attributes
        patch notebook_url(notebook), params: { notebook: new_attributes }
        notebook.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the notebook' do
        notebook = Notebook.create! valid_attributes
        patch notebook_url(notebook), params: { notebook: new_attributes }
        notebook.reload
        expect(response).to redirect_to(notebook_url(notebook))
      end
    end

    context 'with invalid parameters' do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        notebook = Notebook.create! valid_attributes
        patch notebook_url(notebook), params: { notebook: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested notebook' do
      notebook = Notebook.create! valid_attributes
      expect do
        delete notebook_url(notebook)
      end.to change(Notebook, :count).by(-1)
    end

    it 'redirects to the notebooks list' do
      notebook = Notebook.create! valid_attributes
      delete notebook_url(notebook)
      expect(response).to redirect_to(notebooks_url)
    end
  end
end
